title: Pataka Rauranga - Māori Data Hub
subtitle: A place to find data for and about Māori
description: Find and use stats and data about Māori people, language, health, economy, innovation, wellbeing, environment, education, and more.
analytics: false

collections:
  economics:
    output: true
  topics:
    output: true

markdown: kramdown

sass:
    style: compressed
    load_paths:
      - assets/adam-blog/assets/css/sass

include:
  - .htaccess
  - assets/css/main.scss

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - assets/adam-blog/*.html
  - assets/adam-blog/*.json
  - assets/adam-blog/*.md
  - assets/adam-blog/gulpfile.js
  - assets/adam-blog/LICENSE
  - assets/adam-blog/assets/css
  - assets/adam-blog/assets/img
  - assets/adam-blog/assets/js/jquery-3.2.1.min.js